services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080      
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./Pics:/src/Pics
